name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  
jobs:
  build:
    strategy:
      matrix:
        binary: [dtls-decrypter, dtls-encrypter]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
    - name: Get deps
      run: go mod download

    - name: Build
      run: go build ./cmd/${{ matrix.binary }}/main.go
      

    - name: Upload build ${{ matrix.os }}/${{ matrix.binary }}
      uses: actions/upload-artifact@master
      with:
        name: ${{ matrix.binary }}-${{ matrix.os }}
        path: ./main